version: "3.5"

services:
  rinha-api-01:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8080
        - DATABASE_URL=postgresql://admin:123@db:5432/rinha
    hostname: rinha-api-01
    ports:
      - 5000:8080
    environment:
      - DB_HOSTNAME=db
      - DB_INITIAL_POOL_SIZE=13
      - DB_MAX_POOL_SIZE=13
      - API_USE_DB_FUNC=true
      - PORT=8080
      - DATABASE_URL=postgresql://admin:123@db:5432/rinha
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  rinha-api-02:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8080
        - DATABASE_URL=postgresql://admin:123@db:5432/rinha
    hostname: rinha-api-02
    ports:
      - 5001:8080
    environment:
      - DB_HOSTNAME=db
      - DB_INITIAL_POOL_SIZE=13
      - DB_MAX_POOL_SIZE=13
      - API_USE_DB_FUNC=true
      - PORT=8080
      - DATABASE_URL=postgresql://admin:123@db:5432/rinha
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-api-01
      - rinha-api-02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

networks:
  default:
  rinha-network:
